spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/codetemplatepro?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
#    lettuce:
#      pool:
#        max-active: 100
#        # 连接池中的最大空闲连接
#        max-idle: 100
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1
    timeout: 5000

mybatis:
  # 类路径下 mapper文件夹内所有的Mapping配置文件
  mapper-locations: classpath:mapper/*Mapper.xml
#  # 方便我们在resultType里不用写包的全类名，只需要写当前包内的实体类名即可
#  type-aliases-package: com.example.demo.entities