package com.code_template.dao;

import com.code_template.model.po.Depart;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface DepartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Delete({
        "delete from depart",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Insert({
        "insert into depart (id, depart_name, ",
        "description, creator_id, ",
        "gmt_create, gmt_modify)",
        "values (#{id,jdbcType=INTEGER}, #{departName,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{creatorId,jdbcType=INTEGER}, ",
        "#{gmtCreate,jdbcType=TIMESTAMP}, #{gmtModify,jdbcType=TIMESTAMP})"
    })
    int insert(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    int insertSelective(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Select({
        "select",
        "id, depart_name, description, creator_id, gmt_create, gmt_modify",
        "from depart",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.code_template.dao.DepartMapper.BaseResultMap")
    Depart selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    int updateByPrimaryKeySelective(Depart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Update({
        "update depart",
        "set depart_name = #{departName,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "creator_id = #{creatorId,jdbcType=INTEGER},",
          "gmt_create = #{gmtCreate,jdbcType=TIMESTAMP},",
          "gmt_modify = #{gmtModify,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Depart record);
}