package com.code_template.dao;

import com.code_template.model.po.Template;
import org.apache.ibatis.annotations.*;

@Mapper
public interface TemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Delete({
        "delete from template",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Insert({
        "insert into template (id, template_name, ",
        "description, creator_id, ",
        "content, gmt_create, ",
        "gmt_modify)",
        "values (#{id,jdbcType=INTEGER}, #{templateName,jdbcType=VARCHAR}, ",
        "#{description,jdbcType=VARCHAR}, #{creatorId,jdbcType=INTEGER}, ",
        "#{content,jdbcType=VARCHAR}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtModify,jdbcType=TIMESTAMP})"
    })
    int insert(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    int insertSelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Select({
        "select",
        "id, template_name, description, creator_id, content, gmt_create, gmt_modify",
        "from template",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.code_template.dao.TemplateMapper.BaseResultMap")
    Template selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    int updateByPrimaryKeySelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Update({
        "update template",
        "set template_name = #{templateName,jdbcType=VARCHAR},",
          "description = #{description,jdbcType=VARCHAR},",
          "creator_id = #{creatorId,jdbcType=INTEGER},",
          "content = #{content,jdbcType=VARCHAR},",
          "gmt_create = #{gmtCreate,jdbcType=TIMESTAMP},",
          "gmt_modify = #{gmtModify,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Template record);
}