package com.code_template.dao;

import com.code_template.model.po.User;
import org.apache.ibatis.annotations.*;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Delete({
        "delete from user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Insert({
        "insert into user (id, username, ",
        "password, avatar, ",
        "mobile, depart, ",
        "state, last_login_time, ",
        "last_login_ip, gmt_create, ",
        "gmt_modify)",
        "values (#{id,jdbcType=INTEGER}, #{username,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR}, #{avatar,jdbcType=VARCHAR}, ",
        "#{mobile,jdbcType=VARCHAR}, #{depart,jdbcType=INTEGER}, ",
        "#{state,jdbcType=INTEGER}, #{lastLoginTime,jdbcType=TIMESTAMP}, ",
        "#{lastLoginIp,jdbcType=VARCHAR}, #{gmtCreate,jdbcType=TIMESTAMP}, ",
        "#{gmtModify,jdbcType=TIMESTAMP})"
    })
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Select({
        "select",
        "id, username, password, avatar, mobile, depart, state, last_login_time, last_login_ip, ",
        "gmt_create, gmt_modify",
        "from user",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("com.code_template.dao.UserMapper.BaseResultMap")
    User selectByPrimaryKey(Integer id);

    @Select({
            "select",
            "id, username, password, avatar, mobile, depart, state, last_login_time, last_login_ip, ",
            "gmt_create, gmt_modify",
            "from user",
            "where username = #{username,jdbcType=VARCHAR}"
    })
    @ResultMap("com.code_template.dao.UserMapper.BaseResultMap")
    User selectByUsername(String username);

    @Select({
            "select",
            "id, username, password, avatar, mobile, depart, state, last_login_time, last_login_ip, ",
            "gmt_create, gmt_modify",
            "from user",
            "where mobile = #{mobile,jdbcType=VARCHAR}"
    })
    @ResultMap("com.code_template.dao.UserMapper.BaseResultMap")
    User selectByMobile(String mobile);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Update({
        "update user",
        "set username = #{username,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR},",
          "avatar = #{avatar,jdbcType=VARCHAR},",
          "mobile = #{mobile,jdbcType=VARCHAR},",
          "depart = #{depart,jdbcType=INTEGER},",
          "state = #{state,jdbcType=INTEGER},",
          "last_login_time = #{lastLoginTime,jdbcType=TIMESTAMP},",
          "last_login_ip = #{lastLoginIp,jdbcType=VARCHAR},",
          "gmt_create = #{gmtCreate,jdbcType=TIMESTAMP},",
          "gmt_modify = #{gmtModify,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User record);
}