package com.code_template.model.po;

import java.io.Serializable;
import java.util.Date;

public class Depart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.depart_name
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private String departName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.description
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.creator_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.gmt_create
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column depart.gmt_modify
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.id
     *
     * @return the value of depart.id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Depart withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.id
     *
     * @param id the value for depart.id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.depart_name
     *
     * @return the value of depart.depart_name
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public String getDepartName() {
        return departName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Depart withDepartName(String departName) {
        this.setDepartName(departName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.depart_name
     *
     * @param departName the value for depart.depart_name
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setDepartName(String departName) {
        this.departName = departName == null ? null : departName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.description
     *
     * @return the value of depart.description
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Depart withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.description
     *
     * @param description the value for depart.description
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.creator_id
     *
     * @return the value of depart.creator_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Depart withCreatorId(Integer creatorId) {
        this.setCreatorId(creatorId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.creator_id
     *
     * @param creatorId the value for depart.creator_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.gmt_create
     *
     * @return the value of depart.gmt_create
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Depart withGmtCreate(Date gmtCreate) {
        this.setGmtCreate(gmtCreate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.gmt_create
     *
     * @param gmtCreate the value for depart.gmt_create
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column depart.gmt_modify
     *
     * @return the value of depart.gmt_modify
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Depart withGmtModify(Date gmtModify) {
        this.setGmtModify(gmtModify);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column depart.gmt_modify
     *
     * @param gmtModify the value for depart.gmt_modify
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", departName=").append(departName);
        sb.append(", description=").append(description);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append("]");
        return sb.toString();
    }
}