package com.code_template.model.po;

import java.io.Serializable;
import java.util.Date;

public class Template implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.template_name
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private String templateName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.description
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.creator_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Integer creatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.content
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.gmt_create
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column template.gmt_modify
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.id
     *
     * @return the value of template.id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Template withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.id
     *
     * @param id the value for template.id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.template_name
     *
     * @return the value of template.template_name
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public String getTemplateName() {
        return templateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Template withTemplateName(String templateName) {
        this.setTemplateName(templateName);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.template_name
     *
     * @param templateName the value for template.template_name
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setTemplateName(String templateName) {
        this.templateName = templateName == null ? null : templateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.description
     *
     * @return the value of template.description
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Template withDescription(String description) {
        this.setDescription(description);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.description
     *
     * @param description the value for template.description
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.creator_id
     *
     * @return the value of template.creator_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Integer getCreatorId() {
        return creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Template withCreatorId(Integer creatorId) {
        this.setCreatorId(creatorId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.creator_id
     *
     * @param creatorId the value for template.creator_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setCreatorId(Integer creatorId) {
        this.creatorId = creatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.content
     *
     * @return the value of template.content
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Template withContent(String content) {
        this.setContent(content);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.content
     *
     * @param content the value for template.content
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.gmt_create
     *
     * @return the value of template.gmt_create
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Template withGmtCreate(Date gmtCreate) {
        this.setGmtCreate(gmtCreate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.gmt_create
     *
     * @param gmtCreate the value for template.gmt_create
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column template.gmt_modify
     *
     * @return the value of template.gmt_modify
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Template withGmtModify(Date gmtModify) {
        this.setGmtModify(gmtModify);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column template.gmt_modify
     *
     * @param gmtModify the value for template.gmt_modify
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table template
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", templateName=").append(templateName);
        sb.append(", description=").append(description);
        sb.append(", creatorId=").append(creatorId);
        sb.append(", content=").append(content);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append("]");
        return sb.toString();
    }
}