package com.code_template.model.po;

import java.io.Serializable;
import java.util.Date;

public class UserDepart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_depart.id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_depart.depart_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Integer departId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_depart.user_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_depart.gmt_create
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_depart.gmt_modify
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_depart.id
     *
     * @return the value of user_depart.id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public UserDepart withId(Integer id) {
        this.setId(id);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_depart.id
     *
     * @param id the value for user_depart.id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_depart.depart_id
     *
     * @return the value of user_depart.depart_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Integer getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public UserDepart withDepartId(Integer departId) {
        this.setDepartId(departId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_depart.depart_id
     *
     * @param departId the value for user_depart.depart_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setDepartId(Integer departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_depart.user_id
     *
     * @return the value of user_depart.user_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public UserDepart withUserId(Integer userId) {
        this.setUserId(userId);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_depart.user_id
     *
     * @param userId the value for user_depart.user_id
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_depart.gmt_create
     *
     * @return the value of user_depart.gmt_create
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public UserDepart withGmtCreate(Date gmtCreate) {
        this.setGmtCreate(gmtCreate);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_depart.gmt_create
     *
     * @param gmtCreate the value for user_depart.gmt_create
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_depart.gmt_modify
     *
     * @return the value of user_depart.gmt_modify
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public UserDepart withGmtModify(Date gmtModify) {
        this.setGmtModify(gmtModify);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_depart.gmt_modify
     *
     * @param gmtModify the value for user_depart.gmt_modify
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_depart
     *
     * @mbg.generated Thu Jan 28 21:37:17 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", departId=").append(departId);
        sb.append(", userId=").append(userId);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModify=").append(gmtModify);
        sb.append("]");
        return sb.toString();
    }
}